# Generated by Django 4.2.16 on 2024-10-15 18:25

from django.db import migrations, models
import food_delivery.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_rest',
            field=models.ImageField(blank=True, null=True, upload_to=food_delivery.models.rest_photo_directory_path, verbose_name='фото ресторана'),
        ),
    ]
